# coding: utf-8

"""
    티커 및 인디케이터 관리 API

    티커 및 인디케이터를 관리하는 API입니다.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.indicator_calculation_api import router as IndicatorCalculationApiRouter
from openapi_server.apis.indicator_management_api import router as IndicatorManagementApiRouter
from openapi_server.apis.ticker_management_api import router as TickerManagementApiRouter

app = FastAPI(
    title="티커 및 인디케이터 관리 API",
    description="티커 및 인디케이터를 관리하는 API입니다.",
    version="1.0.0",
)

app.include_router(IndicatorCalculationApiRouter)
app.include_router(IndicatorManagementApiRouter)
app.include_router(TickerManagementApiRouter)
